# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    increment_version_code
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end


  lane :icons do
    android_appicon(
      appicon_image_file: '../ios/fastlane/metadata/app_icon.png',
      appicon_icon_types: [:launcher],
      appicon_path: 'app/src/main/res/mipmap'
    )
    android_appicon(
      appicon_image_file: '../ios/fastlane/metadata/app_icon.png',
      appicon_icon_types: [:notification],
      appicon_path: 'app/src/main/res/drawable',
      appicon_filename: 'ic_notification'
    )
  end


  # desc "Deploy a new version to the Google Play"
  # lane :buildDev do
  #   increment_version_code
  #   gradle(task: "clean assembleDevRelease")
  # end

  # desc "Deploy a new version to the Google Play"
  # lane :buildStaging do
  #   increment_version_code
  #   gradle(task: "clean assembleStagingRelease")
  # end

  desc "Deploy a new version to the Google Play"
  lane :buildProduction do
    increment_version_code
    gradle(task: "clean assembleProductionRelease")
  end

  desc "Deploy a new version to the Google Play"
  lane :staging do
    increment_version_code
    gradle(task: "clean assembleStagingRelease")

    appcenter_upload(
      # api_token: "<appcenter token>",
      owner_name: "Komak",
      owner_type: "organization", # Default is user - set to organization for appcenter organizations
      app_name: "komak",
      file: "app/build/outputs/apk/staging/release/app-staging-release.apk",
      notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :production do
    increment_version_code
    gradle(task: "clean assembleProductionRelease")

    appcenter_upload(
      # api_token: "<appcenter token>",
      owner_name: "Komak",
      owner_type: "organization", # Default is user - set to organization for appcenter organizations
      app_name: "komak",
      file: "app/build/outputs/apk/production/release/app-production-release.apk",
      notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :alpha do
    increment_version_code
    gradle(task: "clean bundleProductionRelease")
    upload_to_play_store track:"alpha"
  end
end
